// lib/products.ts
// Base de dades de fons d'inversió per al RoboAdvisor Pro

export type AssetClass =
  | 'renda-variable-global'
  | 'renda-variable-usa'
  | 'renda-variable-europa'
  | 'renda-variable-emergents'
  | 'renda-variable-espanya'
  | 'small-caps-global'
  | 'small-caps-europa'
  | 'renda-fixa-global'
  | 'renda-fixa-europa'
  | 'renda-fixa-curta'
  | 'renda-fixa-alt-rendiment'
  | 'renda-fixa-emergents'
  | 'monetari'
  | 'mixtos'
  | 'etfs-diversificats'
  | 'tecnologia'
  | 'energia'
  | 'salut-biotech'
  | 'dividends-income'
  | 'esg'
  | 'immobiliari-reits';

export type RiskLevel = 1 | 2 | 3 | 4 | 5;
export type InvestorProfile = 'conservador' | 'moderat' | 'dinamic' | 'agressiu';
export type ManagementType = 'indexada' | 'passiva' | 'activa';
export type DataStatus = 'validated' | 'partial' | 'pending' | 'unavailable';

export interface FinancialProduct {
  id: string;
  name: string;
  isin: string;
  manager: string;
  category: string;
  assetClass: AssetClass;
  region: string;
  managementType: ManagementType;
  benchmark: string;
  risk: RiskLevel;
  recommendedProfiles: InvestorProfile[];
  ter: number;                    // TER % anual
  currency: string;
  dataIdentifier?: string;
  dataStatus: DataStatus;
  justification: string;
  tags?: string[];

  // ── Dades quantitatives estimades (base acadèmica) ──────────────────────
  historicalReturn5Y?: number;    // Rendibilitat anualitzada 5Y estimada (%)
  historicalVolatility?: number;  // Volatilitat anualitzada estimada (%)
  maxDrawdownEstimate?: number;   // Màxim drawdown estimat (%, negatiu)
  yieldEstimate?: number;         // Dividend yield / yield estimat (%)
  durationYears?: number;         // Durada modificada per RF (anys)
  inceptionYear?: number;         // Any d'inici del fons
  aum?: number;                   // Actius sota gestió (M EUR, aproximat)

  // ── Classificació professional ───────────────────────────────────────────
  morningstarCategory?: string;   // Categoria Morningstar
  morningstarRating?: 1 | 2 | 3 | 4 | 5;  // Rating Morningstar (si disponible)
  sfdrArticle?: 6 | 8 | 9;        // Classificació SFDR (UE, sostenibilitat)
  mifidRiskIndicator?: 1|2|3|4|5|6|7; // KIID/KID indicator de risc SRI
}

export const FINANCIAL_PRODUCTS: FinancialProduct[] = [

  // ─── MONETARIS ────────────────────────────────────────────────────────────
  {
    id: 'amundi-monetari-eur',
    name: 'Amundi Euro Liquidity SRI',
    isin: 'FR0010510008',
    manager: 'Amundi',
    category: 'Monetari EUR',
    assetClass: 'monetari',
    region: 'Eurozona',
    managementType: 'activa',
    benchmark: 'ESTR Capitalization Index',
    risk: 1,
    recommendedProfiles: ['conservador'],
    ter: 0.10,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Fons monetari de referència per a capital de baix risc. Alta liquiditat i preservació del capital.',
    tags: ['esg', 'liquiditat-alta'],
    historicalReturn5Y:   3.1,
    historicalVolatility: 0.4,
    maxDrawdownEstimate:  -0.2,
    yieldEstimate:        3.2,
    inceptionYear:        2007,
    aum:                  12000,
    morningstarCategory:  'Mercat Monetari EUR',
    morningstarRating:    4,
    sfdrArticle:          8,
    mifidRiskIndicator:   1,
  },
  {
    id: 'bnp-monetari-eur',
    name: 'BNP Paribas InstiCash EUR 1D',
    isin: 'LU0711752370',
    manager: 'BNP Paribas AM',
    category: 'Monetari EUR',
    assetClass: 'monetari',
    region: 'Eurozona',
    managementType: 'activa',
    benchmark: 'ESTR Capitalization Index',
    risk: 1,
    recommendedProfiles: ['conservador'],
    ter: 0.12,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Fons monetari institucional de BNP Paribas, molt líquid i amb gestió conservadora.',
    historicalReturn5Y:   3.0,
    historicalVolatility: 0.3,
    maxDrawdownEstimate:  -0.1,
    yieldEstimate:        3.1,
    inceptionYear:        2011,
    aum:                  8500,
    morningstarCategory:  'Mercat Monetari EUR',
    morningstarRating:    4,
    sfdrArticle:          6,
    mifidRiskIndicator:   1,
  },

  // ─── RENDA FIXA CURTA DURADA ──────────────────────────────────────────────
  {
    id: 'pimco-rf-curta',
    name: 'PIMCO GIS Euro Short-Term Fund',
    isin: 'IE00B11XZ871',
    manager: 'PIMCO',
    category: 'Renda Fixa Curta Durada EUR',
    assetClass: 'renda-fixa-curta',
    region: 'Europa',
    managementType: 'activa',
    benchmark: 'Bloomberg Euro Treasury Bill Index',
    risk: 2,
    recommendedProfiles: ['conservador', 'moderat'],
    ter: 0.45,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Fons de renda fixa de curta durada gestionat per PIMCO. Redueix sensibilitat als tipus d\'interès.',
    historicalReturn5Y:   2.4,
    historicalVolatility: 1.8,
    maxDrawdownEstimate:  -3.5,
    yieldEstimate:        3.6,
    durationYears:        1.2,
    inceptionYear:        2004,
    aum:                  3200,
    morningstarCategory:  'RF Curta Durada EUR',
    morningstarRating:    4,
    sfdrArticle:          8,
    mifidRiskIndicator:   2,
  },
  {
    id: 'vanguard-rf-curta-eur',
    name: 'Vanguard Euro Government Bond Index Fund',
    isin: 'IE00B04GQQ17',
    manager: 'Vanguard',
    category: 'Renda Fixa Govern Europa Curta',
    assetClass: 'renda-fixa-curta',
    region: 'Europa',
    managementType: 'indexada',
    benchmark: 'Bloomberg Euro Government Float Adjusted Bond Index',
    risk: 2,
    recommendedProfiles: ['conservador', 'moderat'],
    ter: 0.12,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Fons indexat de deute públic europeu de Vanguard. Molt baix cost i diversificació governamental.',
    historicalReturn5Y:   1.8,
    historicalVolatility: 2.2,
    maxDrawdownEstimate:  -4.8,
    yieldEstimate:        3.2,
    durationYears:        6.5,
    inceptionYear:        2009,
    aum:                  6100,
    morningstarCategory:  'RF Govern Global EUR',
    morningstarRating:    4,
    sfdrArticle:          6,
    mifidRiskIndicator:   2,
  },

  // ─── RENDA FIXA GLOBAL ────────────────────────────────────────────────────
  {
    id: 'templeton-rf-global',
    name: 'Franklin Templeton Global Bond Fund',
    isin: 'LU0152980495',
    manager: 'Franklin Templeton',
    category: 'Renda Fixa Global',
    assetClass: 'renda-fixa-global',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'FTSE World Government Bond Index (USD Hedged)',
    risk: 3,
    recommendedProfiles: ['conservador', 'moderat'],
    ter: 0.68,
    currency: 'USD',
    dataStatus: 'partial',
    justification: 'Referent mundial en renda fixa global activa. Gestió flexible i diversificació internacional.',
    historicalReturn5Y:   1.2,
    historicalVolatility: 6.5,
    maxDrawdownEstimate:  -12.0,
    yieldEstimate:        4.2,
    durationYears:        4.5,
    inceptionYear:        2002,
    aum:                  4800,
    morningstarCategory:  'RF Global',
    morningstarRating:    3,
    sfdrArticle:          6,
    mifidRiskIndicator:   3,
  },
  {
    id: 'pimco-rf-global',
    name: 'PIMCO GIS Global Bond Fund',
    isin: 'IE0031488521',
    manager: 'PIMCO',
    category: 'Renda Fixa Global',
    assetClass: 'renda-fixa-global',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'Bloomberg Global Aggregate Bond Index (USD Hedged)',
    risk: 3,
    recommendedProfiles: ['conservador', 'moderat'],
    ter: 0.55,
    currency: 'USD',
    dataStatus: 'partial',
    justification: 'Un dels fons de renda fixa global de referència mundial. Gestió activa de durada i divisa.',
    historicalReturn5Y:   1.8,
    historicalVolatility: 5.2,
    maxDrawdownEstimate:  -10.5,
    yieldEstimate:        4.5,
    durationYears:        5.8,
    inceptionYear:        1997,
    aum:                  22000,
    morningstarCategory:  'RF Global',
    morningstarRating:    4,
    sfdrArticle:          8,
    mifidRiskIndicator:   3,
  },

  // ─── RENDA FIXA EUROPEA ───────────────────────────────────────────────────
  {
    id: 'nordea-rf-europa',
    name: 'Nordea 1 European High Yield Bond Fund',
    isin: 'LU0141799501',
    manager: 'Nordea AM',
    category: 'Renda Fixa Alt Rendiment Europa',
    assetClass: 'renda-fixa-europa',
    region: 'Europa',
    managementType: 'activa',
    benchmark: 'ICE BofA European Currency High Yield Index',
    risk: 3,
    recommendedProfiles: ['moderat', 'dinamic'],
    ter: 0.75,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Exposició a deute corporatiu europeu d\'alt rendiment. Complement de risc/rendibilitat interessant.',
    historicalReturn5Y:   4.5,
    historicalVolatility: 7.8,
    maxDrawdownEstimate:  -18.0,
    yieldEstimate:        6.2,
    durationYears:        3.2,
    inceptionYear:        2000,
    aum:                  1900,
    morningstarCategory:  'RF Alt Rendiment EUR',
    morningstarRating:    4,
    sfdrArticle:          8,
    mifidRiskIndicator:   3,
  },

  // ─── RENDA VARIABLE GLOBAL ────────────────────────────────────────────────
  {
    id: 'msif-global-opp',
    name: 'Morgan Stanley IF Global Opportunity Fund',
    isin: 'LU0552385295',
    manager: 'Morgan Stanley IM',
    category: 'Renda Variable Global Growth',
    assetClass: 'renda-variable-global',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'MSCI World Net Return Index',
    risk: 4,
    recommendedProfiles: ['dinamic', 'agressiu'],
    ter: 1.05,
    currency: 'USD',
    dataStatus: 'partial',
    justification: 'Fons de creixement global de referència. Selecció d\'empreses d\'alta qualitat amb avantatges competitius.',
    historicalReturn5Y:   10.2,
    historicalVolatility: 19.5,
    maxDrawdownEstimate:  -38.0,
    inceptionYear:        2010,
    aum:                  14800,
    morningstarCategory:  'RV Global Creixement',
    morningstarRating:    5,
    sfdrArticle:          8,
    mifidRiskIndicator:   6,
  },
  {
    id: 'fundsmith-equity',
    name: 'Fundsmith Equity Fund T Acc',
    isin: 'GB00B41YBW71',
    manager: 'Fundsmith',
    category: 'Renda Variable Global Quality',
    assetClass: 'renda-variable-global',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'MSCI World Index',
    risk: 4,
    recommendedProfiles: ['dinamic', 'agressiu'],
    ter: 0.94,
    currency: 'GBP',
    dataStatus: 'partial',
    justification: 'Estratègia "buy and hold" de qualitat. Un dels fons de gestió activa global amb millor track record europeu.',
    historicalReturn5Y:   12.1,
    historicalVolatility: 15.8,
    maxDrawdownEstimate:  -28.5,
    inceptionYear:        2010,
    aum:                  23000,
    morningstarCategory:  'RV Global Barrja',
    morningstarRating:    5,
    sfdrArticle:          6,
    mifidRiskIndicator:   5,
  },
  {
    id: 'vanguard-global-index',
    name: 'Vanguard Global Stock Index Fund EUR',
    isin: 'IE00B03HCZ61',
    manager: 'Vanguard',
    category: 'Renda Variable Global Indexada',
    assetClass: 'renda-variable-global',
    region: 'Global',
    managementType: 'indexada',
    benchmark: 'MSCI World Index',
    risk: 4,
    recommendedProfiles: ['moderat', 'dinamic', 'agressiu'],
    ter: 0.18,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Fons indexat global de referència. Molt baix cost, màxima diversificació i seguiment eficient del MSCI World.',
    historicalReturn5Y:   13.5,
    historicalVolatility: 14.8,
    maxDrawdownEstimate:  -33.0,
    inceptionYear:        2003,
    aum:                  58000,
    morningstarCategory:  'RV Global Barrja',
    morningstarRating:    4,
    sfdrArticle:          6,
    mifidRiskIndicator:   5,
  },
  {
    id: 'amundi-msci-world',
    name: 'Amundi Index MSCI World Fund',
    isin: 'LU0996182563',
    manager: 'Amundi',
    category: 'Renda Variable Global Indexada',
    assetClass: 'renda-variable-global',
    region: 'Global',
    managementType: 'indexada',
    benchmark: 'MSCI World Index',
    risk: 4,
    recommendedProfiles: ['moderat', 'dinamic'],
    ter: 0.18,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Alternativa indexada d\'Amundi al MSCI World. Accessible per a inversors europeus amb TER competitiu.',
    historicalReturn5Y:   13.4,
    historicalVolatility: 14.9,
    maxDrawdownEstimate:  -33.2,
    inceptionYear:        2012,
    aum:                  9200,
    morningstarCategory:  'RV Global Barrja',
    morningstarRating:    4,
    sfdrArticle:          8,
    mifidRiskIndicator:   5,
  },

  // ─── RENDA VARIABLE USA ───────────────────────────────────────────────────
  {
    id: 'baillie-gifford-usa',
    name: 'Baillie Gifford American Fund',
    isin: 'GB0005765085',
    manager: 'Baillie Gifford',
    category: 'Renda Variable USA Growth',
    assetClass: 'renda-variable-usa',
    region: 'EUA',
    managementType: 'activa',
    benchmark: 'S&P 500 Index',
    risk: 5,
    recommendedProfiles: ['dinamic', 'agressiu'],
    ter: 0.51,
    currency: 'GBP',
    dataStatus: 'partial',
    justification: 'Fons nord-americà de creixement amb enfocament a empreses transformadores. Llarg termini i convicció alta.',
    historicalReturn5Y:   14.8,
    historicalVolatility: 25.2,
    maxDrawdownEstimate:  -55.0,
    inceptionYear:        1997,
    aum:                  7400,
    morningstarCategory:  'RV EUA Creixement',
    morningstarRating:    3,
    sfdrArticle:          6,
    mifidRiskIndicator:   6,
  },
  {
    id: 'vanguard-usa-index',
    name: 'Vanguard U.S. 500 Stock Index Fund EUR',
    isin: 'IE0032620787',
    manager: 'Vanguard',
    category: 'Renda Variable USA Indexada',
    assetClass: 'renda-variable-usa',
    region: 'EUA',
    managementType: 'indexada',
    benchmark: 'S&P 500 Index',
    risk: 5,
    recommendedProfiles: ['dinamic', 'agressiu'],
    ter: 0.10,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Fons indexat S&P 500 de Vanguard. El més eficient per a exposició als EUA a cost mínima.',
    historicalReturn5Y:   16.8,
    historicalVolatility: 16.2,
    maxDrawdownEstimate:  -34.0,
    inceptionYear:        2000,
    aum:                  31000,
    morningstarCategory:  'RV EUA Barrja',
    morningstarRating:    5,
    sfdrArticle:          6,
    mifidRiskIndicator:   5,
  },

  // ─── RENDA VARIABLE EUROPA ────────────────────────────────────────────────
  {
    id: 'fidelity-europa',
    name: 'Fidelity Funds European Growth Fund',
    isin: 'LU0048578792',
    manager: 'Fidelity',
    category: 'Renda Variable Europa',
    assetClass: 'renda-variable-europa',
    region: 'Europa',
    managementType: 'activa',
    benchmark: 'MSCI Europe Index',
    risk: 4,
    recommendedProfiles: ['moderat', 'dinamic'],
    ter: 0.91,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Fons europeu de creixement de Fidelity. Gestió activa amb selecció rigorosa d\'empreses europees de qualitat.',
    historicalReturn5Y:   9.2,
    historicalVolatility: 15.5,
    maxDrawdownEstimate:  -32.0,
    inceptionYear:        1990,
    aum:                  5200,
    morningstarCategory:  'RV Europa Creixement',
    morningstarRating:    4,
    sfdrArticle:          8,
    mifidRiskIndicator:   5,
  },
  {
    id: 'threadneedle-europa',
    name: 'Threadneedle European Select Fund',
    isin: 'GB0002771169',
    manager: 'Columbia Threadneedle',
    category: 'Renda Variable Europa Select',
    assetClass: 'renda-variable-europa',
    region: 'Europa',
    managementType: 'activa',
    benchmark: 'MSCI Europe Index',
    risk: 4,
    recommendedProfiles: ['moderat', 'dinamic'],
    ter: 0.83,
    currency: 'GBP',
    dataStatus: 'partial',
    justification: 'Selecció concentrada de les millors empreses europees. Track record consistent i equip gestor experimentat.',
    historicalReturn5Y:   8.5,
    historicalVolatility: 14.8,
    maxDrawdownEstimate:  -30.0,
    inceptionYear:        1992,
    aum:                  3100,
    morningstarCategory:  'RV Europa Barrja',
    morningstarRating:    4,
    sfdrArticle:          6,
    mifidRiskIndicator:   5,
  },

  // ─── RENDA VARIABLE ESPANYA ───────────────────────────────────────────────
  {
    id: 'bestinver-bolsa',
    name: 'Bestinver Bolsa FI',
    isin: 'ES0110407072',
    manager: 'Bestinver',
    category: 'Renda Variable Espanya',
    assetClass: 'renda-variable-espanya',
    region: 'Espanya',
    managementType: 'activa',
    benchmark: 'IGBM (Índice General Bolsa Madrid)',
    risk: 5,
    recommendedProfiles: ['dinamic', 'agressiu'],
    ter: 1.50,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Referent de la gestió activa espanyola. Filosofia value amb una de les millors trajectòries del mercat ibèric.',
    historicalReturn5Y:   8.5,
    historicalVolatility: 18.5,
    maxDrawdownEstimate:  -42.0,
    inceptionYear:        1992,
    aum:                  1850,
    morningstarCategory:  'RV Espanya',
    morningstarRating:    4,
    sfdrArticle:          8,
    mifidRiskIndicator:   6,
  },
  {
    id: 'cobas-iberia',
    name: 'Cobas Iberia FI',
    isin: 'ES0119459002',
    manager: 'Cobas AM',
    category: 'Renda Variable Ibèria',
    assetClass: 'renda-variable-espanya',
    region: 'Espanya / Portugal',
    managementType: 'activa',
    benchmark: 'IGBM',
    risk: 5,
    recommendedProfiles: ['agressiu'],
    ter: 1.75,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Fons value ibèric concentrat. Alta convicció i llarg termini. Adequat per a inversors amb alta tolerància a volatilitat.',
    historicalReturn5Y:   5.2,
    historicalVolatility: 22.0,
    maxDrawdownEstimate:  -52.0,
    inceptionYear:        2017,
    aum:                  280,
    morningstarCategory:  'RV Espanya',
    morningstarRating:    2,
    sfdrArticle:          6,
    mifidRiskIndicator:   6,
  },

  // ─── MERCATS EMERGENTS ────────────────────────────────────────────────────
  {
    id: 'gqg-emergents',
    name: 'GQG Partners Emerging Markets Equity Fund',
    isin: 'IE00BD7HRT35',
    manager: 'GQG Partners',
    category: 'Renda Variable Mercats Emergents',
    assetClass: 'renda-variable-emergents',
    region: 'Emergents Global',
    managementType: 'activa',
    benchmark: 'MSCI Emerging Markets Index',
    risk: 5,
    recommendedProfiles: ['dinamic', 'agressiu'],
    ter: 0.75,
    currency: 'USD',
    dataStatus: 'partial',
    justification: 'Una de les gestores emergents de major creixement global. Enfocament qualitatiu i gestió flexible.',
    historicalReturn5Y:   11.8,
    historicalVolatility: 18.5,
    maxDrawdownEstimate:  -35.0,
    inceptionYear:        2016,
    aum:                  18200,
    morningstarCategory:  'RV Mercats Emergents',
    morningstarRating:    5,
    sfdrArticle:          8,
    mifidRiskIndicator:   6,
  },
  {
    id: 'fidelity-emergents',
    name: 'Fidelity Funds Emerging Markets Fund',
    isin: 'LU0048615250',
    manager: 'Fidelity',
    category: 'Renda Variable Mercats Emergents',
    assetClass: 'renda-variable-emergents',
    region: 'Emergents Global',
    managementType: 'activa',
    benchmark: 'MSCI Emerging Markets Index',
    risk: 5,
    recommendedProfiles: ['dinamic', 'agressiu'],
    ter: 1.00,
    currency: 'USD',
    dataStatus: 'partial',
    justification: 'Fons d\'emergents amb llarg track record de Fidelity. Selecció bottom-up rigorosa.',
    historicalReturn5Y:   6.2,
    historicalVolatility: 19.2,
    maxDrawdownEstimate:  -38.0,
    inceptionYear:        1990,
    aum:                  5800,
    morningstarCategory:  'RV Mercats Emergents',
    morningstarRating:    3,
    sfdrArticle:          8,
    mifidRiskIndicator:   6,
  },

  // ─── SMALL CAPS GLOBAL ────────────────────────────────────────────────────
  {
    id: 'hermes-small-caps-global',
    name: 'Federated Hermes Global Small Companies Fund',
    isin: 'IE00B3NFJB90',
    manager: 'Federated Hermes',
    category: 'Renda Variable Small Caps Global',
    assetClass: 'small-caps-global',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'MSCI World Small Cap Index',
    risk: 5,
    recommendedProfiles: ['dinamic', 'agressiu'],
    ter: 0.90,
    currency: 'USD',
    dataStatus: 'partial',
    justification: 'Accés a petites capitalitzacions globals. Prima de liquiditat i potencial de creixement superior a llarg termini.',
    historicalReturn5Y:   9.8,
    historicalVolatility: 19.5,
    maxDrawdownEstimate:  -40.0,
    inceptionYear:        2008,
    aum:                  980,
    morningstarCategory:  'RV Global Small/Mid Cap',
    morningstarRating:    4,
    sfdrArticle:          8,
    mifidRiskIndicator:   6,
  },

  // ─── SMALL CAPS EUROPA ────────────────────────────────────────────────────
  {
    id: 'lonvia-small-caps-europa',
    name: 'Lonvia Avenir Mid-Cap Euro Fund',
    isin: 'FR0011716477',
    manager: 'Lonvia AM',
    category: 'Renda Variable Small/Mid Caps Europa',
    assetClass: 'small-caps-europa',
    region: 'Europa',
    managementType: 'activa',
    benchmark: 'MSCI Europe Small Cap Index',
    risk: 5,
    recommendedProfiles: ['dinamic', 'agressiu'],
    ter: 1.50,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Referent europeu en petites i mitjanes capitalitzacions. Equip gestor de gran reputació (antic Comgest).',
    historicalReturn5Y:   7.5,
    historicalVolatility: 20.5,
    maxDrawdownEstimate:  -43.0,
    inceptionYear:        2013,
    aum:                  1100,
    morningstarCategory:  'RV Europa Small/Mid Cap',
    morningstarRating:    4,
    sfdrArticle:          8,
    mifidRiskIndicator:   6,
  },

  // ─── TECNOLOGIA ───────────────────────────────────────────────────────────
  {
    id: 'polar-capital-tech',
    name: 'Polar Capital Technology Trust',
    isin: 'GB0007021389',
    manager: 'Polar Capital',
    category: 'Renda Variable Tecnologia Global',
    assetClass: 'tecnologia',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'Dow Jones Global Technology Index',
    risk: 5,
    recommendedProfiles: ['dinamic', 'agressiu'],
    ter: 0.85,
    currency: 'GBP',
    dataStatus: 'partial',
    justification: 'Referent en tecnologia global. Equip especialitzat amb gran coneixement sectorial. Alta volatilitat.',
    historicalReturn5Y:   18.5,
    historicalVolatility: 22.0,
    maxDrawdownEstimate:  -42.0,
    inceptionYear:        1996,
    aum:                  3200,
    morningstarCategory:  'Sectorial Tecnologia',
    morningstarRating:    5,
    sfdrArticle:          6,
    mifidRiskIndicator:   6,
  },
  {
    id: 'bgf-world-technology',
    name: 'BlackRock GF World Technology Fund',
    isin: 'LU0171310443',
    manager: 'BlackRock',
    category: 'Renda Variable Tecnologia Global',
    assetClass: 'tecnologia',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'NYSE World Technology Index',
    risk: 5,
    recommendedProfiles: ['agressiu'],
    ter: 1.75,
    currency: 'USD',
    dataStatus: 'partial',
    justification: 'Fons tecnològic de BlackRock amb gran diversificació global. Alta convicció en empreses d\'innovació.',
    historicalReturn5Y:   19.2,
    historicalVolatility: 23.5,
    maxDrawdownEstimate:  -45.0,
    inceptionYear:        2001,
    aum:                  9800,
    morningstarCategory:  'Sectorial Tecnologia',
    morningstarRating:    4,
    sfdrArticle:          6,
    mifidRiskIndicator:   6,
  },

  // ─── ENERGIA ──────────────────────────────────────────────────────────────
  {
    id: 'bgf-world-energy',
    name: 'BlackRock GF World Energy Fund',
    isin: 'LU0122376428',
    manager: 'BlackRock',
    category: 'Renda Variable Energia Global',
    assetClass: 'energia',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'MSCI World Energy Index',
    risk: 5,
    recommendedProfiles: ['agressiu'],
    ter: 1.75,
    currency: 'USD',
    dataStatus: 'partial',
    justification: 'Exposició concentrada al sector energètic global. Alta volatilitat i correlació amb preu del petroli.',
    historicalReturn5Y:   12.8,
    historicalVolatility: 26.5,
    maxDrawdownEstimate:  -62.0,
    inceptionYear:        2001,
    aum:                  1200,
    morningstarCategory:  'Sectorial Energia',
    morningstarRating:    3,
    sfdrArticle:          6,
    mifidRiskIndicator:   6,
  },

  // ─── SALUT / BIOTECNOLOGIA ────────────────────────────────────────────────
  {
    id: 'polar-capital-healthcare',
    name: 'Polar Capital Global Healthcare Fund',
    isin: 'IE00B3MGYV59',
    manager: 'Polar Capital',
    category: 'Renda Variable Salut Global',
    assetClass: 'salut-biotech',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'MSCI World Health Care Index',
    risk: 4,
    recommendedProfiles: ['dinamic', 'agressiu'],
    ter: 1.00,
    currency: 'USD',
    dataStatus: 'partial',
    justification: 'Especialistes en salut global. Diversificació entre farmacèutiques, biotec i dispositius mèdics.',
    historicalReturn5Y:   9.5,
    historicalVolatility: 14.0,
    maxDrawdownEstimate:  -28.0,
    inceptionYear:        2007,
    aum:                  2800,
    morningstarCategory:  'Sectorial Salut',
    morningstarRating:    5,
    sfdrArticle:          8,
    mifidRiskIndicator:   5,
  },
  {
    id: 'bellevue-biotech',
    name: 'BB Biotech AG',
    isin: 'CH0038389992',
    manager: 'Bellevue AM',
    category: 'Renda Variable Biotecnologia',
    assetClass: 'salut-biotech',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'NYSE Arca Biotechnology Index',
    risk: 5,
    recommendedProfiles: ['agressiu'],
    ter: 1.10,
    currency: 'CHF',
    dataStatus: 'partial',
    justification: 'Referent en biotecnologia global. Alta concentració i volatilitat, però potencial excepcional a llarg termini.',
    historicalReturn5Y:   5.2,
    historicalVolatility: 28.5,
    maxDrawdownEstimate:  -55.0,
    inceptionYear:        1993,
    aum:                  1900,
    morningstarCategory:  'Sectorial Biotecnologia',
    morningstarRating:    3,
    sfdrArticle:          6,
    mifidRiskIndicator:   7,
  },

  // ─── DIVIDENDS / INCOME ───────────────────────────────────────────────────
  {
    id: 'fidelity-dividend',
    name: 'Fidelity Funds Global Dividend Fund',
    isin: 'LU0605515377',
    manager: 'Fidelity',
    category: 'Renda Variable Dividends Global',
    assetClass: 'dividends-income',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'MSCI World Index',
    risk: 3,
    recommendedProfiles: ['moderat', 'dinamic'],
    ter: 0.80,
    currency: 'USD',
    dataStatus: 'partial',
    justification: 'Fons d\'ingressos per dividends global. Empreses de qualitat i rendiment consistent. Menys volatilitat que el mercat.',
    historicalReturn5Y:   9.8,
    historicalVolatility: 11.5,
    maxDrawdownEstimate:  -24.0,
    yieldEstimate:        3.5,
    inceptionYear:        2012,
    aum:                  4200,
    morningstarCategory:  'RV Global Income',
    morningstarRating:    5,
    sfdrArticle:          8,
    mifidRiskIndicator:   4,
  },
  {
    id: 'threadneedle-dividends',
    name: 'Threadneedle Global Equity Income Fund',
    isin: 'GB00B6TQRF09',
    manager: 'Columbia Threadneedle',
    category: 'Renda Variable Income Global',
    assetClass: 'dividends-income',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'MSCI World High Dividend Yield Index',
    risk: 3,
    recommendedProfiles: ['moderat', 'dinamic'],
    ter: 0.85,
    currency: 'GBP',
    dataStatus: 'partial',
    justification: 'Combinació de creixement i ingressos. Cartera diversificada de pagadors de dividends sostenibles.',
    historicalReturn5Y:   8.5,
    historicalVolatility: 12.0,
    maxDrawdownEstimate:  -25.5,
    yieldEstimate:        4.0,
    inceptionYear:        2014,
    aum:                  1800,
    morningstarCategory:  'RV Global Income',
    morningstarRating:    4,
    sfdrArticle:          8,
    mifidRiskIndicator:   4,
  },

  // ─── ESG / SOSTENIBLE ─────────────────────────────────────────────────────
  {
    id: 'pictet-esg-global',
    name: 'Pictet Global Environmental Opportunities Fund',
    isin: 'LU0503631714',
    manager: 'Pictet AM',
    category: 'Renda Variable ESG Global',
    assetClass: 'esg',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'MSCI World Index',
    risk: 4,
    recommendedProfiles: ['moderat', 'dinamic'],
    ter: 1.20,
    currency: 'USD',
    dataStatus: 'partial',
    justification: 'Pioner en inversió temàtica sostenible. Enfocament en empreses d\'eficiència de recursos i medi ambient.',
    tags: ['esg', 'sostenible', 'temàtic'],
    historicalReturn5Y:   10.2,
    historicalVolatility: 16.5,
    maxDrawdownEstimate:  -35.0,
    inceptionYear:        2010,
    aum:                  4800,
    morningstarCategory:  'RV Global Medi Ambient',
    morningstarRating:    5,
    sfdrArticle:          9,
    mifidRiskIndicator:   5,
  },
  {
    id: 'nordea-esg-global',
    name: 'Nordea 1 Global Climate and Environment Fund',
    isin: 'LU0348926287',
    manager: 'Nordea AM',
    category: 'Renda Variable ESG Clima',
    assetClass: 'esg',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'MSCI World Index',
    risk: 4,
    recommendedProfiles: ['moderat', 'dinamic'],
    ter: 1.50,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Referent en inversió climàtica. Empreses amb solucions de transició energètica i eficiència ambiental.',
    tags: ['esg', 'sostenible', 'clima'],
    historicalReturn5Y:   9.8,
    historicalVolatility: 17.0,
    maxDrawdownEstimate:  -36.0,
    inceptionYear:        2008,
    aum:                  2200,
    morningstarCategory:  'RV Global Medi Ambient',
    morningstarRating:    4,
    sfdrArticle:          9,
    mifidRiskIndicator:   5,
  },

  // ─── IMMOBILIARI / REITs ──────────────────────────────────────────────────
  {
    id: 'cohen-steers-reits',
    name: 'Cohen & Steers SICAV Global Real Estate Securities Fund',
    isin: 'LU0209137388',
    manager: 'Cohen & Steers',
    category: 'Immobiliari Global (REITs)',
    assetClass: 'immobiliari-reits',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'FTSE EPRA/NAREIT Global Index',
    risk: 4,
    recommendedProfiles: ['moderat', 'dinamic'],
    ter: 1.15,
    currency: 'USD',
    dataStatus: 'partial',
    justification: 'Especialistes mundials en REITs globals. Exposició a immobiliari cotitzat diversificat internacionalment.',
    historicalReturn5Y:   5.2,
    historicalVolatility: 17.5,
    maxDrawdownEstimate:  -40.0,
    yieldEstimate:        3.8,
    inceptionYear:        2006,
    aum:                  1500,
    morningstarCategory:  'Sectorial Immobiliari Indirect Global',
    morningstarRating:    4,
    sfdrArticle:          6,
    mifidRiskIndicator:   5,
  },
  {
    id: 'janus-henderson-reits',
    name: 'Janus Henderson Horizon Global Property Equities Fund',
    isin: 'LU0088927925',
    manager: 'Janus Henderson',
    category: 'Immobiliari Global',
    assetClass: 'immobiliari-reits',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'FTSE EPRA/NAREIT Global Index',
    risk: 4,
    recommendedProfiles: ['moderat', 'dinamic'],
    ter: 1.05,
    currency: 'USD',
    dataStatus: 'partial',
    justification: 'Llarg track record en immobiliari global. Alta diversificació geogràfica i per subsectors immobiliaris.',
    historicalReturn5Y:   4.8,
    historicalVolatility: 16.8,
    maxDrawdownEstimate:  -42.0,
    yieldEstimate:        3.5,
    inceptionYear:        1997,
    aum:                  2100,
    morningstarCategory:  'Sectorial Immobiliari Indirect Global',
    morningstarRating:    4,
    sfdrArticle:          6,
    mifidRiskIndicator:   5,
  },

  // ─── ETFs DIVERSIFICATS ────────────────────────────────────────────────────

  {
    id: 'ishares-msci-world-etf',
    name: 'iShares Core MSCI World UCITS ETF USD Acc',
    isin: 'IE00B4L5Y983',
    manager: 'BlackRock iShares',
    category: 'ETF Renda Variable Global',
    assetClass: 'etfs-diversificats',
    region: 'Global Desenvolupat',
    managementType: 'indexada',
    benchmark: 'MSCI World Index',
    risk: 4,
    recommendedProfiles: ['moderat', 'dinamic', 'agressiu'],
    ter: 0.20,
    currency: 'USD',
    dataIdentifier: 'IWDA.AS',
    dataStatus: 'validated',
    justification: 'ETF de referència mundial. Cobertura de 1.500+ empreses de 23 mercats desenvolupats. El més recomanat per a la base d\'una cartera indexada global. TER competitiu i AuM màxim del sector.',
    tags: ['etf', 'indexat', 'world', 'core'],
    historicalReturn5Y:   12.8,
    historicalVolatility: 14.2,
    maxDrawdownEstimate:  -33.0,
    inceptionYear:        2009,
    aum:                  75000,
    morningstarCategory:  'RV Global Cap. Gran Blend',
    morningstarRating:    5,
    sfdrArticle:          6,
    mifidRiskIndicator:   4,
  },
  {
    id: 'vanguard-ftse-all-world-etf',
    name: 'Vanguard FTSE All-World UCITS ETF USD Dist',
    isin: 'IE00B3RBWM25',
    manager: 'Vanguard',
    category: 'ETF Renda Variable Global',
    assetClass: 'etfs-diversificats',
    region: 'Global (Desen. + Emergents)',
    managementType: 'indexada',
    benchmark: 'FTSE All-World Index',
    risk: 4,
    recommendedProfiles: ['moderat', 'dinamic', 'agressiu'],
    ter: 0.22,
    currency: 'USD',
    dataIdentifier: 'VWRL.AS',
    dataStatus: 'validated',
    justification: 'Cobertura total del mercat mundial incloent emergents (aprox. 90% de la capitalització global). Ideal per a inversors que volen un sol ETF per representar tot el mercat. Distribueix dividend trimestralment.',
    tags: ['etf', 'indexat', 'world', 'emergents', 'dividend'],
    historicalReturn5Y:   11.9,
    historicalVolatility: 14.8,
    maxDrawdownEstimate:  -34.5,
    yieldEstimate:        1.8,
    inceptionYear:        2012,
    aum:                  18000,
    morningstarCategory:  'RV Global Cap. Gran Blend',
    morningstarRating:    5,
    sfdrArticle:          6,
    mifidRiskIndicator:   4,
  },
  {
    id: 'spdr-sp500-etf',
    name: 'SPDR S&P 500 UCITS ETF USD Dist',
    isin: 'IE00B6YX5C33',
    manager: 'State Street SPDR',
    category: 'ETF Renda Variable EUA',
    assetClass: 'etfs-diversificats',
    region: 'Estats Units',
    managementType: 'indexada',
    benchmark: 'S&P 500 Index',
    risk: 4,
    recommendedProfiles: ['dinamic', 'agressiu'],
    ter: 0.03,
    currency: 'USD',
    dataIdentifier: 'SPY5.DE',
    dataStatus: 'validated',
    justification: 'Réplica del S&P 500 amb el TER més baix del mercat europeu (0,03%). Exposició pura a les 500 majors empreses nord-americanes. Ideal per a la component core d\'una cartera amb biaix USA.',
    tags: ['etf', 'indexat', 'sp500', 'usa', 'ter-baix'],
    historicalReturn5Y:   14.2,
    historicalVolatility: 15.1,
    maxDrawdownEstimate:  -33.9,
    yieldEstimate:        1.3,
    inceptionYear:        2012,
    aum:                  45000,
    morningstarCategory:  'RV Gran Cap. Blend EUA',
    morningstarRating:    5,
    sfdrArticle:          6,
    mifidRiskIndicator:   4,
  },
  {
    id: 'ishares-msci-em-etf',
    name: 'iShares Core MSCI Emerging Markets UCITS ETF USD Acc',
    isin: 'IE00BKM4GZ66',
    manager: 'BlackRock iShares',
    category: 'ETF Renda Variable Emergents',
    assetClass: 'etfs-diversificats',
    region: 'Mercats Emergents',
    managementType: 'indexada',
    benchmark: 'MSCI Emerging Markets IMI Index',
    risk: 5,
    recommendedProfiles: ['dinamic', 'agressiu'],
    ter: 0.18,
    currency: 'USD',
    dataIdentifier: 'EMIM.AS',
    dataStatus: 'validated',
    justification: 'El ETF de referència per a emergents a Europa. Cobreix 24 mercats emergents incloent Xina, Índia, Brasil i Taiwan. Component important en carteres dinàmiques amb horitzó llarg.',
    tags: ['etf', 'indexat', 'emergents'],
    historicalReturn5Y:   4.8,
    historicalVolatility: 18.5,
    maxDrawdownEstimate:  -38.0,
    inceptionYear:        2014,
    aum:                  22000,
    morningstarCategory:  'RV Mercats Emergents Global',
    morningstarRating:    4,
    sfdrArticle:          6,
    mifidRiskIndicator:   5,
  },
  {
    id: 'ishares-global-agg-bond-etf',
    name: 'iShares Core Global Aggregate Bond UCITS ETF EUR Hedged Acc',
    isin: 'IE00B3F81R35',
    manager: 'BlackRock iShares',
    category: 'ETF Renda Fixa Global',
    assetClass: 'etfs-diversificats',
    region: 'Global',
    managementType: 'indexada',
    benchmark: 'Bloomberg Global Aggregate Bond Index (EUR Hedged)',
    risk: 2,
    recommendedProfiles: ['conservador', 'moderat'],
    ter: 0.10,
    currency: 'EUR',
    dataIdentifier: 'AGGH.AS',
    dataStatus: 'validated',
    justification: 'Exposició a renda fixa global diversificada (governs + corporatius IG) amb cobertura de divisa EUR. Component defensiu ideal per a carteres conservadores i moderades. Baix cost i alta diversificació.',
    tags: ['etf', 'indexat', 'renda-fixa', 'hedged', 'core'],
    historicalReturn5Y:   1.2,
    historicalVolatility: 4.8,
    maxDrawdownEstimate:  -18.5,
    durationYears:        6.8,
    inceptionYear:        2017,
    aum:                  9500,
    morningstarCategory:  'RF Global EUR Hedged',
    morningstarRating:    4,
    sfdrArticle:          6,
    mifidRiskIndicator:   3,
  },
  {
    id: 'amundi-msci-world-sri-etf',
    name: 'Amundi MSCI World SRI UCITS ETF DR EUR (C)',
    isin: 'LU1861134382',
    manager: 'Amundi ETF',
    category: 'ETF Renda Variable Global ESG',
    assetClass: 'etfs-diversificats',
    region: 'Global Desenvolupat',
    managementType: 'indexada',
    benchmark: 'MSCI World SRI 5% Capped Index',
    risk: 4,
    recommendedProfiles: ['moderat', 'dinamic'],
    ter: 0.18,
    currency: 'EUR',
    dataIdentifier: 'WSRI.PA',
    dataStatus: 'partial',
    justification: 'ETF ESG de referència a Europa. Filtra les empreses del MSCI World per criteris ambientals, socials i de governança (ESG). Ideal per a inversors que volen exposició global amb component sostenible. TER competitiu.',
    tags: ['etf', 'indexat', 'esg', 'sri', 'world'],
    historicalReturn5Y:   13.1,
    historicalVolatility: 14.5,
    maxDrawdownEstimate:  -32.5,
    inceptionYear:        2018,
    aum:                  4200,
    morningstarCategory:  'RV Global Cap. Gran Blend',
    morningstarRating:    4,
    sfdrArticle:          8,
    mifidRiskIndicator:   4,
  },
  {
    id: 'ishares-core-europe-etf',
    name: 'iShares Core MSCI Europe UCITS ETF EUR Dist',
    isin: 'IE00B4K48X80',
    manager: 'BlackRock iShares',
    category: 'ETF Renda Variable Europa',
    assetClass: 'etfs-diversificats',
    region: 'Europa',
    managementType: 'indexada',
    benchmark: 'MSCI Europe Index',
    risk: 4,
    recommendedProfiles: ['moderat', 'dinamic'],
    ter: 0.12,
    currency: 'EUR',
    dataIdentifier: 'IMEU.AS',
    dataStatus: 'validated',
    justification: 'ETF de renda variable europea a cost mínimo. Cobreix 15 mercats europeus desenvolupats amb 430+ empreses. Component core per a carteres amb biaix europeu. Distribueix dividend.',
    tags: ['etf', 'indexat', 'europa', 'dividend'],
    historicalReturn5Y:   8.9,
    historicalVolatility: 13.8,
    maxDrawdownEstimate:  -35.0,
    yieldEstimate:        2.8,
    inceptionYear:        2010,
    aum:                  8200,
    morningstarCategory:  'RV Europa Cap. Gran Blend',
    morningstarRating:    5,
    sfdrArticle:          6,
    mifidRiskIndicator:   4,
  },
  {
    id: 'xtrackers-msci-world-etf',
    name: 'Xtrackers MSCI World Swap UCITS ETF 1C',
    isin: 'LU0274208692',
    manager: 'DWS Xtrackers',
    category: 'ETF Renda Variable Global',
    assetClass: 'etfs-diversificats',
    region: 'Global Desenvolupat',
    managementType: 'indexada',
    benchmark: 'MSCI World Index (Net Total Return)',
    risk: 4,
    recommendedProfiles: ['moderat', 'dinamic', 'agressiu'],
    ter: 0.19,
    currency: 'USD',
    dataIdentifier: 'XMWO.DE',
    dataStatus: 'validated',
    justification: 'ETF MSCI World via swap de DWS amb alta eficiència fiscal. Alternativa al iShares IWDA per a inversors que volen diversificar de proveïdor. Cost molt competitiu i alta liquiditat en borsa europea.',
    tags: ['etf', 'indexat', 'world', 'swap'],
    historicalReturn5Y:   12.6,
    historicalVolatility: 14.3,
    maxDrawdownEstimate:  -33.2,
    inceptionYear:        2007,
    aum:                  5800,
    morningstarCategory:  'RV Global Cap. Gran Blend',
    morningstarRating:    5,
    sfdrArticle:          6,
    mifidRiskIndicator:   4,
  },

  // ─── FONS MIXTOS ──────────────────────────────────────────────────────────

  {
    id: 'flossbach-multiple-opp',
    name: 'Flossbach von Storch SICAV - Multiple Opportunities R',
    isin: 'LU0323578657',
    manager: 'Flossbach von Storch',
    category: 'Mixt Flexible Global',
    assetClass: 'mixtos',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'Cap benchmark formal',
    risk: 3,
    recommendedProfiles: ['moderat', 'dinamic'],
    ter: 1.56,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Un dels millors fons mixtos d\'Europa per track record i consistència. Gestió flexible sense restriccions de pes. Pot invertir en or físic (fins al 15%). Equip gestor molt reputat, liderat per Bert Flossbach.',
    tags: ['mixt', 'flexible', 'or', 'actiu'],
    historicalReturn5Y:   6.8,
    historicalVolatility: 9.2,
    maxDrawdownEstimate:  -22.0,
    inceptionYear:        2007,
    aum:                  14500,
    morningstarCategory:  'Mixt Flexible Global',
    morningstarRating:    5,
    sfdrArticle:          6,
    mifidRiskIndicator:   3,
  },
  {
    id: 'nordea-stable-return',
    name: 'Nordea 1 - Stable Return Fund BI EUR',
    isin: 'LU0141799501',
    manager: 'Nordea AM',
    category: 'Mixt Flexible Global',
    assetClass: 'mixtos',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'Cap benchmark formal',
    risk: 2,
    recommendedProfiles: ['conservador', 'moderat'],
    ter: 1.00,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Fons mixt defensiu orientat a la preservació del capital amb retorn estable. Combina renda variable de baixa volatilitat amb renda fixa seleccionada. Historial robust en períodes de turbulències de mercat.',
    tags: ['mixt', 'defensiu', 'preservació-capital'],
    historicalReturn5Y:   3.9,
    historicalVolatility: 5.8,
    maxDrawdownEstimate:  -12.5,
    inceptionYear:        2005,
    aum:                  6200,
    morningstarCategory:  'Mixt Defensiu Global',
    morningstarRating:    4,
    sfdrArticle:          8,
    mifidRiskIndicator:   3,
  },
  {
    id: 'jpmorgan-global-income',
    name: 'JPMorgan Investment Funds - Global Income Fund A (div) EUR',
    isin: 'LU0861555025',
    manager: 'JPMorgan AM',
    category: 'Mixt Income Global',
    assetClass: 'mixtos',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'Cap benchmark formal',
    risk: 3,
    recommendedProfiles: ['conservador', 'moderat'],
    ter: 1.27,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Fons d\'income multi-actiu de referència. Genera rendes periòdiques combinant dividends, cupons i primes d\'opcions. Ideal per a inversors que necesiten flux de caixa. Distribució mensual.',
    tags: ['mixt', 'income', 'dividend', 'multi-actiu'],
    historicalReturn5Y:   4.8,
    historicalVolatility: 7.1,
    maxDrawdownEstimate:  -16.0,
    yieldEstimate:        4.2,
    inceptionYear:        2012,
    aum:                  20000,
    morningstarCategory:  'Mixt Moderat Global',
    morningstarRating:    4,
    sfdrArticle:          6,
    mifidRiskIndicator:   3,
  },
  {
    id: 'dws-kaldemorgen',
    name: 'DWS Concept Kaldemorgen EUR LC',
    isin: 'LU0599946893',
    manager: 'DWS',
    category: 'Mixt Flexible Global',
    assetClass: 'mixtos',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'Cap benchmark formal',
    risk: 3,
    recommendedProfiles: ['moderat'],
    ter: 1.52,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Fons mixt flexible gestionat per Klaus Kaldemorgen, llegenda de la gestió activa a Europa. Objectiu de volatilitat màxima del 10% i drawdown limitat. Perfil de risc/retorn molt atractiu per a moderats.',
    tags: ['mixt', 'flexible', 'baixa-volatilitat'],
    historicalReturn5Y:   4.2,
    historicalVolatility: 6.8,
    maxDrawdownEstimate:  -14.0,
    inceptionYear:        2011,
    aum:                  5100,
    morningstarCategory:  'Mixt Flexible Global',
    morningstarRating:    4,
    sfdrArticle:          8,
    mifidRiskIndicator:   3,
  },

  // ─── RENDA FIXA ALT RENDIMENT ─────────────────────────────────────────────

  {
    id: 'pimco-high-yield',
    name: 'PIMCO GIS Global High Yield Bond Fund E Acc EUR Hdg',
    isin: 'IE0034235016',
    manager: 'PIMCO',
    category: 'Renda Fixa Alt Rendiment Global',
    assetClass: 'renda-fixa-alt-rendiment',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'ICE BofA Global High Yield BB-B Constrained Index',
    risk: 4,
    recommendedProfiles: ['dinamic'],
    ter: 0.89,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Exposició a deute corporatiu d\'alt rendiment global gestionada per PIMCO, referent mundial en renda fixa. Combina yield atractiu (6-8%) amb gestió activa del risc de crèdit. Component de rendiment en carteres dinàmiques.',
    tags: ['high-yield', 'crèdit', 'actiu'],
    historicalReturn5Y:   5.1,
    historicalVolatility: 9.8,
    maxDrawdownEstimate:  -24.5,
    yieldEstimate:        7.2,
    durationYears:        3.8,
    inceptionYear:        1997,
    aum:                  3800,
    morningstarCategory:  'RF Alt Rendiment Global',
    morningstarRating:    4,
    sfdrArticle:          6,
    mifidRiskIndicator:   4,
  },
  {
    id: 'ishares-hy-bond-etf',
    name: 'iShares Euro High Yield Corporate Bond UCITS ETF EUR Dist',
    isin: 'IE00B66F4759',
    manager: 'BlackRock iShares',
    category: 'ETF Renda Fixa Alt Rendiment EUR',
    assetClass: 'renda-fixa-alt-rendiment',
    region: 'Europa',
    managementType: 'indexada',
    benchmark: 'Markit iBoxx EUR Liquid High Yield Index',
    risk: 3,
    recommendedProfiles: ['moderat', 'dinamic'],
    ter: 0.50,
    currency: 'EUR',
    dataStatus: 'validated',
    justification: 'ETF de referència per a high yield europeu. Ofereix yield del 5-7% amb diversificació entre 400+ emisors. Cost molt inferior als fons actius equivalents. Alternativa eficient per a exposició a crèdit europeu.',
    tags: ['etf', 'high-yield', 'europa', 'corporatiu'],
    historicalReturn5Y:   4.6,
    historicalVolatility: 8.2,
    maxDrawdownEstimate:  -22.0,
    yieldEstimate:        6.1,
    durationYears:        3.2,
    inceptionYear:        2012,
    aum:                  7200,
    morningstarCategory:  'RF Alt Rendiment EUR',
    morningstarRating:    4,
    sfdrArticle:          6,
    mifidRiskIndicator:   3,
  },

  // ─── RENDA FIXA EMERGENTS ─────────────────────────────────────────────────

  {
    id: 'pimco-em-bond',
    name: 'PIMCO GIS Emerging Markets Bond Fund E Acc EUR Hdg',
    isin: 'IE00B11XZ871',
    manager: 'PIMCO',
    category: 'Renda Fixa Emergents',
    assetClass: 'renda-fixa-emergents',
    region: 'Mercats Emergents',
    managementType: 'activa',
    benchmark: 'JPMorgan EMBI Global Index',
    risk: 4,
    recommendedProfiles: ['dinamic'],
    ter: 0.91,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Deute emergent en divisa forta gestionat per PIMCO. Combina yield superior (5-8%) amb risc de crèdit i de país. Diversificació valuosa en carteres dinàmiques que busquen rendiment addicional.',
    tags: ['emergents', 'renda-fixa', 'actiu', 'hedged'],
    historicalReturn5Y:   3.8,
    historicalVolatility: 10.5,
    maxDrawdownEstimate:  -26.0,
    yieldEstimate:        6.5,
    durationYears:        5.5,
    inceptionYear:        2002,
    aum:                  4500,
    morningstarCategory:  'RF Mercats Emergents Divisa Forta',
    morningstarRating:    4,
    sfdrArticle:          6,
    mifidRiskIndicator:   4,
  },

  // ─── RENDA VARIABLE GLOBAL — ADDICIONALS ─────────────────────────────────

  {
    id: 'capital-group-world-growth',
    name: 'Capital Group World Growth and Income (LUX) B',
    isin: 'LU1295551144',
    manager: 'Capital Group',
    category: 'Renda Variable Global',
    assetClass: 'renda-variable-global',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'MSCI All Country World Index',
    risk: 4,
    recommendedProfiles: ['moderat', 'dinamic'],
    ter: 0.88,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Gestió activa de Capital Group (gestor de referència als EUA) amb combinació de creixement i dividend. Estil multi-gestor intern que aporta diversificació d\'estils. Historial sòlid a llarg termini.',
    tags: ['renda-variable', 'global', 'dividend', 'actiu'],
    historicalReturn5Y:   11.2,
    historicalVolatility: 13.5,
    maxDrawdownEstimate:  -31.0,
    yieldEstimate:        1.5,
    inceptionYear:        2016,
    aum:                  6800,
    morningstarCategory:  'RV Global Cap. Gran Blend',
    morningstarRating:    4,
    sfdrArticle:          6,
    mifidRiskIndicator:   4,
  },
  {
    id: 'comgest-growth-world',
    name: 'Comgest Growth World USD Acc',
    isin: 'IE0033535182',
    manager: 'Comgest',
    category: 'Renda Variable Global Creixement',
    assetClass: 'renda-variable-global',
    region: 'Global',
    managementType: 'activa',
    benchmark: 'MSCI All Country World Index',
    risk: 4,
    recommendedProfiles: ['dinamic', 'agressiu'],
    ter: 1.50,
    currency: 'USD',
    dataStatus: 'partial',
    justification: 'Focus en qualitat i creixement a llarg termini. Comgest selecciona empreses amb avantatges competitius duraderes i alt ROIC. Cartera concentrada (40-50 valors) i baix turnover. Gestora independent i reputada.',
    tags: ['renda-variable', 'global', 'quality', 'creixement', 'concentrat'],
    historicalReturn5Y:   10.8,
    historicalVolatility: 14.8,
    maxDrawdownEstimate:  -34.0,
    inceptionYear:        2000,
    aum:                  1800,
    morningstarCategory:  'RV Global Cap. Gran Creixement',
    morningstarRating:    4,
    sfdrArticle:          8,
    mifidRiskIndicator:   5,
  },

  // ─── RENDA VARIABLE USA — ADDICIONALS ────────────────────────────────────

  {
    id: 'brown-advisory-us-equity',
    name: 'Brown Advisory US Equity Growth Fund B USD Acc',
    isin: 'IE00BF5CZM90',
    manager: 'Brown Advisory',
    category: 'Renda Variable EUA Creixement',
    assetClass: 'renda-variable-usa',
    region: 'Estats Units',
    managementType: 'activa',
    benchmark: 'Russell 1000 Growth Index',
    risk: 5,
    recommendedProfiles: ['agressiu'],
    ter: 0.75,
    currency: 'USD',
    dataStatus: 'partial',
    justification: 'Cartera concentrada en empreses nord-americanes de creixement de qualitat. Brown Advisory és reconeguda per la seva disciplina de selecció bottom-up. Ideal per a inversors agressius amb alt convicció en tecnologia i innovació.',
    tags: ['usa', 'creixement', 'quality', 'concentrat'],
    historicalReturn5Y:   15.8,
    historicalVolatility: 18.5,
    maxDrawdownEstimate:  -39.0,
    inceptionYear:        2014,
    aum:                  3200,
    morningstarCategory:  'RV Gran Cap. Creixement EUA',
    morningstarRating:    5,
    sfdrArticle:          6,
    mifidRiskIndicator:   5,
  },

  // ─── RENDA VARIABLE EUROPA — ADDICIONALS ─────────────────────────────────

  {
    id: 'comgest-growth-europe',
    name: 'Comgest Growth Europe Acc EUR',
    isin: 'IE0004766014',
    manager: 'Comgest',
    category: 'Renda Variable Europa Creixement',
    assetClass: 'renda-variable-europa',
    region: 'Europa',
    managementType: 'activa',
    benchmark: 'MSCI Europe Index',
    risk: 4,
    recommendedProfiles: ['dinamic', 'agressiu'],
    ter: 1.64,
    currency: 'EUR',
    dataStatus: 'partial',
    justification: 'Un dels millors fons d\'inversió europeus per consistència de retorns. Selecció de 30-40 empreses europees de qualitat excepcional. Historial de 30+ anys que supera sistemàticament l\'índex a llarg termini.',
    tags: ['europa', 'quality', 'creixement', 'concentrat'],
    historicalReturn5Y:   9.5,
    historicalVolatility: 13.2,
    maxDrawdownEstimate:  -31.5,
    inceptionYear:        1991,
    aum:                  2900,
    morningstarCategory:  'RV Europa Cap. Gran Creixement',
    morningstarRating:    5,
    sfdrArticle:          8,
    mifidRiskIndicator:   5,
  },

  // ─── CONSERVADOR — RENDA FIXA ADDICIONALS ────────────────────────────────

  {
    id: 'vanguard-euro-gov-bond-etf',
    name: 'Vanguard EUR Eurozone Government Bond UCITS ETF',
    isin: 'IE00BZ163L38',
    manager: 'Vanguard',
    category: 'ETF Renda Fixa Governs Eurozona',
    assetClass: 'renda-fixa-europa',
    region: 'Eurozona',
    managementType: 'indexada',
    benchmark: 'Bloomberg Euro Treasury Bond Index',
    risk: 2,
    recommendedProfiles: ['conservador', 'moderat'],
    ter: 0.07,
    currency: 'EUR',
    dataIdentifier: 'VGEA.AS',
    dataStatus: 'validated',
    justification: 'ETF de deute sobirà de la Eurozona al cost més baix (0,07% TER). Component defensiu pur per a carteres conservadores. Cobertura total del mercat de governs EUR sense risc de divisa.',
    tags: ['etf', 'indexat', 'governs', 'eurozona', 'ter-baix'],
    historicalReturn5Y:   0.8,
    historicalVolatility: 5.5,
    maxDrawdownEstimate:  -19.0,
    yieldEstimate:        3.1,
    durationYears:        7.5,
    inceptionYear:        2018,
    aum:                  1800,
    morningstarCategory:  'RF Governs EUR',
    morningstarRating:    4,
    sfdrArticle:          6,
    mifidRiskIndicator:   3,
  },
];

// ─── HELPERS ──────────────────────────────────────────────────────────────────

export function getProductById(id: string): FinancialProduct | undefined {
  return FINANCIAL_PRODUCTS.find(p => p.id === id);
}

export function getProductsByAssetClass(assetClass: AssetClass): FinancialProduct[] {
  return FINANCIAL_PRODUCTS.filter(p => p.assetClass === assetClass);
}

export function getProductsByProfile(profile: InvestorProfile): FinancialProduct[] {
  return FINANCIAL_PRODUCTS.filter(p => p.recommendedProfiles.includes(profile));
}

export function getDataStatusLabel(status: DataStatus): string {
  const labels: Record<DataStatus, string> = {
    validated: '✅ Dades validades',
    partial: '⚠️ Dades parcials',
    pending: '🕐 Pendent de dades',
    unavailable: '❌ Dades no disponibles',
  };
  return labels[status];
}

export function getDataStatusColor(status: DataStatus): string {
  const colors: Record<DataStatus, string> = {
    validated:   'bg-green-100 text-green-800',
    partial:     'bg-yellow-100 text-yellow-800',
    pending:     'bg-blue-100 text-blue-800',
    unavailable: 'bg-red-100 text-red-800',
  };
  return colors[status];
}

export function getSFDRLabel(article?: 6 | 8 | 9): string {
  if (!article) return 'No classificat';
  const labels = { 6: 'Art. 6 — Sense objectiu sostenible', 8: 'Art. 8 — Promou criteris ESG', 9: 'Art. 9 — Objectiu sostenible' };
  return labels[article];
}

export function getSFDRColor(article?: 6 | 8 | 9): string {
  if (!article) return 'bg-gray-100 text-gray-600';
  const colors = { 6: 'bg-gray-100 text-gray-700', 8: 'bg-blue-100 text-blue-800', 9: 'bg-green-100 text-green-800' };
  return colors[article];
}

export function getMorningstarStars(rating?: number): string {
  if (!rating) return '—';
  return '★'.repeat(rating) + '☆'.repeat(5 - rating);
}

export function getRiskIndicatorLabel(sriRisk?: number): string {
  if (!sriRisk) return '—';
  const labels: Record<number, string> = { 1: 'SRI 1 - Molt Baix', 2: 'SRI 2 - Baix', 3: 'SRI 3 - Mig-Baix', 4: 'SRI 4 - Mig', 5: 'SRI 5 - Mig-Alt', 6: 'SRI 6 - Alt', 7: 'SRI 7 - Molt Alt' };
  return labels[sriRisk] ?? `SRI ${sriRisk}`;
}

export function getProductStats() {
  const total    = FINANCIAL_PRODUCTS.length;
  const byClass  = FINANCIAL_PRODUCTS.reduce<Record<string, number>>((acc, p) => {
    acc[p.assetClass] = (acc[p.assetClass] ?? 0) + 1;
    return acc;
  }, {});
  const avgTER   = FINANCIAL_PRODUCTS.reduce((s, p) => s + p.ter, 0) / total;
  const withESG  = FINANCIAL_PRODUCTS.filter(p => p.sfdrArticle && p.sfdrArticle >= 8).length;
  const indexed  = FINANCIAL_PRODUCTS.filter(p => p.managementType === 'indexada').length;
  return { total, byClass, avgTER: Math.round(avgTER * 1000) / 1000, withESG, indexed };
}